{"name": "falla la prueba", "status": "failed", "statusDetails": {"message": "AssertionError: 'Enter Admin' != 'Login Page'\n- Enter Admin\n+ Login Page\n\n", "trace": "  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 234, in step_impl\n    Boton_Login_fail.resultado(context)\n  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\pages_objects\\boton_fail_login_po.py\", line 42, in resultado\n    assercion.assertEqual(value, resultado)\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 837, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 1217, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 667, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Given usuario un app mobile", "status": "passed", "start": 1635555854110, "stop": 1635555856488}, {"name": "When el usuario hace click en login boton", "status": "passed", "start": 1635555856488, "stop": 1635555857620}, {"name": "And no coloca las credenciales", "status": "passed", "start": 1635555857620, "stop": 1635555859635}, {"name": "And hace click en login sin credenciales", "status": "passed", "start": 1635555859636, "stop": 1635555859803}, {"name": "Then le deja iniciar sesion", "status": "failed", "statusDetails": {"message": "AssertionError: 'Enter Admin' != 'Login Page'\n- Enter Admin\n+ Login Page\n\n", "trace": "  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 234, in step_impl\n    Boton_Login_fail.resultado(context)\n  File \"C:\\Users\\pedroluis\\PycharmProjects\\appiumavalith\\pages_objects\\boton_fail_login_po.py\", line 42, in resultado\n    assercion.assertEqual(value, resultado)\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 837, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 1217, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\pedroluis\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py\", line 667, in fail\n    raise self.failureException(msg)\n"}, "start": 1635555859803, "stop": 1635555860308}], "start": 1635555854110, "stop": 1635555860309, "uuid": "63747381-3d40-45de-8bb3-94c3dc274f66", "historyId": "685cd0b24c81e6058bc17e5b51872270", "fullName": "probar demo apk: falla la prueba", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "feature"}, {"name": "tag", "value": "testcasefail"}, {"name": "feature", "value": "probar demo apk"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}